export const mutationTypes = {
  SET_MENU_MOBILE_OPEN: 'SET_MENU_MOBILE_OPEN',
  SET_SLIDE_COLOR: 'SET_SLIDE_COLOR',
  SET_SLIDE_TONE: 'SET_SLIDE_TONE',
  SET_SLIDE_CONFIG: 'SET_SLIDE_CONFIG',
  SET_PAGE_META: 'SET_PAGE_META'
}
